export const defaultCopy: Record<string, string> = {
  "app.title": "Betaalpauze aanvragen",
  "app.subtitle": "Vraag eenvoudig een betaalpauze aan. Wij helpen je met het versturen van je verzoek.",
  "step1.question": "Bij welke organisatie heb je de rekening openstaan?",
  "step1.helperText": "Typ de naam van het bedrijf of incassobureau.",
  "step1.placeholder": "Zoek een organisatie...",
  "step2.question": "Welk bedrag moet je betalen?",
  "step2.helperText": "Vul het openstaande bedrag in.",
  "step2.placeholder": "0,00",
  "step3.question": "Wat is je factuurnummer?",
  "step3.helperText": "Je vindt het factuurnummer op de brief of e-mail die je hebt ontvangen.",
  "step3.placeholder": "bijv. FAC-2024-001",
  "step3.noInvoice": "Ik heb geen factuurnummer",
  "step4.question": "Wat is je geboortedatum?",
  "step4.helperText": "Met je geboortedatum kan de organisatie je factuur makkelijker terugvinden. Ze mogen je geboortedatum niet zelf opzoeken.",
  "step5.question": "Wat is je voornaam?",
  "step5.placeholder": "bijv. Jan",
  "step6.question": "Wat is je achternaam?",
  "step6.placeholder": "bijv. De Vries",
  "step7.question": "Wat is je e-mailadres?",
  "step7.helperText": "Hierop ontvang je een bevestiging van je verzoek.",
  "step7.placeholder": "bijv. jan@voorbeeld.nl",
  "step8.question": "Wat is je telefoonnummer?",
  "step8.helperText": "Niet verplicht, maar het maakt contact makkelijker.",
  "step8.placeholder": "bijv. 06 12345678",
  "review.title": "Controleer je gegevens",
  "review.subtitle": "Kijk of alles klopt voordat je het verzoek verstuurt.",
  "review.sectionOrganisation": "Organisatie",
  "review.sectionAmount": "Bedrag",
  "review.sectionInvoice": "Factuurnummer of geboortedatum",
  "review.sectionPersonal": "Persoonsgegevens",
  "review.emailPreviewTitle": "Voorbeeld van het e-mailbericht",
  "button.next": "Volgende",
  "button.back": "Terug",
  "button.submit": "Verstuur verzoek",
  "button.edit": "Wijzig",
  "button.newRequest": "Nieuwe aanvraag starten",
  "error.required": "Dit veld is verplicht.",
  "error.invalidEmail": "Vul een geldig e-mailadres in.",
  "error.invalidAmount": "Vul een geldig bedrag in dat hoger is dan 0.",
  "error.invalidDate": "Vul een geldige geboortedatum in.",
  "error.invoiceOrBirthdate": "Vul je geboortedatum in als je geen factuurnummer hebt.",
  "email.subject": "Verzoek betaalpauze",
  "email.greeting": "Beste",
  "email.body": "Ik heb op dit moment moeite om deze rekening op tijd te betalen. Daarom wil ik graag een betaalpauze aanvragen.",
  "email.detailsHeader": "Mijn gegevens:",
  "email.labelName": "Naam",
  "email.labelEmail": "E-mail",
  "email.labelPhone": "Telefoonnummer",
  "email.labelAmount": "Openstaand bedrag",
  "email.labelInvoice": "Factuurnummer",
  "email.labelBirthDate": "Geboortedatum",
  "email.closing": "Ik hoor graag of dit mogelijk is.",
  "email.signoff": "Met vriendelijke groet,",
  "success.title": "Je verzoek is verstuurd!",
  "success.message": "We hebben je betaalpauze-verzoek verstuurd naar de organisatie. Je ontvangt een bevestiging op je e-mailadres.",
  "success.whatNext": "Wat nu?",
  "success.whatNextDescription": "De organisatie bekijkt je verzoek en neemt zo snel mogelijk contact met je op. Dit duurt meestal 5 tot 10 werkdagen.",
  "loading.text": "Teksten laden...",
  "label.firstName": "Voornaam",
  "label.lastName": "Achternaam",
  "label.email": "E-mailadres",
  "label.phone": "Telefoonnummer",
  "label.company": "Organisatie",
  "label.amount": "Bedrag",
  "label.invoice": "Factuurnummer",
  "label.birthDate": "Geboortedatum",
}
